FROM node:alpine
WORKDIR '/app'
COPY ./package.json .
RUN yarn install
COPY . .
# RUN chmod a+x app/node_modules/.bin/react-scripts
RUN chmod +x ./node_modules/.bin/react-scripts
CMD ["yarn", "start"]