version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: fib_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./hisab_nikash_db:/var/lib/postgresql/data/
  adminer:
    container_name: fib_db_client_tool
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  redis:
    image: redis:latest
    container_name: fib_redis

  
  nginx:
    depends_on:
      - api
      - client
    container_name: fib_nginx
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    container_name: fib_server
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fib_db
      - PGPORT=5432
  client:
    container_name: fib_client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    container_name: fib_worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app

