version: '3'
services:
  web:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./app:/app

    